version: '3.8'

services:
  api_biblioteca:
    container_name: trab_api_node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: segredissimo_muito_forte_aqui
      PG_USER: user_api
      PG_PASSWORD: senhasegura
      PG_DB: crud_alunos
      PG_HOST: postgres_db 
    depends_on:
      - postgres_db 
    networks:
      - biblioteca_net

  postgres_db:
    container_name: trab_api_postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: user_api
      POSTGRES_PASSWORD: senhasegura
      POSTGRES_DB: crud_alunos
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - biblioteca_net

volumes:
  pgdata:
networks:
  biblioteca_net:
    driver: bridge